# SPDX-FileCopyrightText: 2025-2026 Tyrone Ross, Jr <46267523+tyroneross@users.noreply.github.com>
# SPDX-License-Identifier: Apache-2.0

[package]
name = "rally-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "rally"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
notify = "6"
rally-core = { path = "../rally-core" }
rally-protocol = { path = "../rally-protocol" }
rally-trust = { path = "../rally-trust" }
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[dev-dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
